Gradient generation
bobbobow2/BV_BIOCAD pull request #1
Opened 2024-07-18 08:44 UTC by Murkat-git

Commit containing some utils and method to optimize antibody sequence with gradient

2024-07-18 09:02 UTC, Nik9kin commented on utils/general.py
> +    return x is not None
Зачем и импортируешь exists, и сам пишешь?

2024-07-18 13:28 UTC, Nik9kin requested changes

2024-07-18 13:28 UTC, Nik9kin commented on utils/general.py
> +                mask[pos.number] = torch.ones(5)
Работает некорректно. Обсудили почему: pos.number это **не** то же самое, что 0-based index

2024-07-18 13:28 UTC, Nik9kin commented on utils/general.py
> +        assert self.coords is not None
assert-ов лучше избегать в зрелом коде, потому что они не дают понимания произошедшей ошибки.
```suggestion
        if self.coords is None:
            raise ValueError('no coordinates data')
```

2024-07-18 13:28 UTC, Nik9kin commented on utils/scorer.py
> +    return x is not None
Опять?)

2024-07-18 13:28 UTC, Nik9kin commented on optimizers/gradient.py
> +    ).mean(-1)
```suggestion
    ).sum(-1)
```

2024-07-18 13:28 UTC, Nik9kin commented on optimizers/gradient.py
> +        ).sum() / mask.mean(-1).sum()
```suggestion
    rmsd_sq = torch.sum(mse * mask, dim=(-2, -1)) / mask.mean(-1).sum()
```

2024-07-18 13:28 UTC, Nik9kin commented on optimizers/gradient.py
> +    return mse
```suggestion
    return rmsd_sq
```

2024-07-18 13:33 UTC, Nik9kin commented on optimizers/gradient.py
> +        self.logits[0][vh_cdr_mask==1] = self.logits[0][vh_cdr_mask==1].where(self.logits[0][vh_cdr_mask==1]!=0, torch.tensor([-np.inf], device=device))
Что здесь происходит? Я не могу понять. Зачем это нужно?

2024-07-18 13:34 UTC, Nik9kin commented on optimizers/gradient.py
> +        self.logits[0][vh_cdr_mask==1] = self.logits[0][vh_cdr_mask==1].where(self.logits[0][vh_cdr_mask==1]!=0, torch.tensor([-np.inf], device=device))
Что здесь происходит? Я не могу понять. Зачем это нужно?

2024-07-18 19:14 UTC, Murkat-git commented on utils/general.py
> +    return x is not None
Дань уважения коллегам

2024-07-19 12:03 UTC, Nik9kin approved these changes

2024-07-19 12:04 UTC, merged